version: '3.8'

x-healthcheck:
  &healthcheck
  test: curl -f http://localhost/
  interval: 5s
  timeout: 5s
  retries: 5
  start_period: 5s

services:
  db:
    image: postgres:14.5
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    restart: always
    networks:
      - custom
    healthcheck:
      <<: *healthcheck
      test: pg_isready -U ${POSTGRES_USER:-postgres} -d ${POSTGRES_DB:-postgres}
      
  task:
    build: .
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_HOST: ${POSTGRES_HOST}
      ADMIN_USERNAME: ${ADMIN_USERNAME}
      ADMIN_PASSWORD: ${ADMIN_PASSWORD}
    depends_on:
      db:
        condition: service_healthy
    restart: always
    ports:
      - "8080:8000"
    networks:
     - custom

networks:
  custom:
    driver: bridge
